"use client";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { communicationRepository } from "@/lib/communication-repository";
import type { ChatMessage, Conversation } from "@/lib/types";
import { useMediaPermission } from "@/hooks/use-media-permission";
import { CallOverlay } from "./call-overlay";
import styles from "./chat-panel.module.css";

export function ChatPanel({ compact=false,onMinimize }: {compact?:boolean;onMinimize?:()=>void}) {
  const [conversations,setConversations]=useState<Conversation[]>([]); const [conversationId,setConversationId]=useState<string>(); const [messages,setMessages]=useState<ChatMessage[]>([]); const [text,setText]=useState(""); const [file,setFile]=useState<File>(); const [error,setError]=useState(""); const [callId,setCallId]=useState<string>(); const [recording,setRecording]=useState(false); const recorder=useRef<MediaRecorder | undefined>(undefined); const chunks=useRef<Blob[]>([]); const {request,stop,state}=useMediaPermission();
  const load=useCallback(async()=>{try{const data=await communicationRepository.listConversations();setConversations(data);if(!conversationId&&data[0])setConversationId(data[0].id);}catch(e){setError(e instanceof Error?e.message:"Could not load messages.");}},[conversationId]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(!conversationId)return;const refresh=async()=>{try{setMessages(await communicationRepository.messages(conversationId));await communicationRepository.read(conversationId);}catch(e){setError(e instanceof Error?e.message:"Could not load messages.");}};void refresh();const channel=communicationRepository.subscribe(conversationId,refresh);return()=>{void channel.unsubscribe();};},[conversationId]);
  const start=async()=>{try{const id=await communicationRepository.start();setConversationId(id);await load();}catch(e){setError(e instanceof Error?e.message:"Could not start support chat.");}};
  const send=async(e:FormEvent)=>{e.preventDefault();if(!conversationId||(!text&&!file))return;try{await communicationRepository.send(conversationId,text,file?.type.startsWith("image/")?"image":file?"file":"text",file);setText("");setFile(undefined);}catch(e){setError(e instanceof Error?e.message:"Could not send message.");}};
  const toggleRecording=async()=>{try{if(recording){recorder.current?.stop();return;}const stream=await request();chunks.current=[];const media=new MediaRecorder(stream);recorder.current=media;media.ondataavailable=e=>chunks.current.push(e.data);media.onstop=async()=>{setRecording(false);stop();const blob=new Blob(chunks.current,{type:media.mimeType||"audio/webm"});if(!conversationId)return;const voice=new File([blob],`voice-note-${Date.now()}.${media.mimeType.includes("mp4")?"m4a":"webm"}`,{type:blob.type});try{await communicationRepository.send(conversationId,"","voice_note",voice,Math.min(120000,Math.round((chunks.current.reduce((n,x)=>n+x.size,0)/16000)*1000)));}catch(e){setError(e instanceof Error?e.message:"Could not send voice note.");}};media.start();setRecording(true);}catch(e){setError(e instanceof Error?e.message:"Microphone access is required to record a voice note.");}};
  const call=async()=>{if(!conversationId)return;try{setCallId(await communicationRepository.requestCall(conversationId));}catch(e){setError(e instanceof Error?e.message:"Could not start call.");}};
  return <section className={styles.chat}><header className={styles.header}><span className={styles.avatar}>M</span><div><h2>MarketApp Support</h2><small>Online</small></div>{compact&&<button className={styles.icon} onClick={onMinimize}>−</button>}<button className={styles.icon} onClick={call}>☎</button></header>{error&&<p>{error}</p>}<main className={styles.thread}>{!conversationId&&<button className={styles.icon} onClick={start}>Start chat</button>}{messages.map(message=><article key={message.id} className={`${styles.bubble} ${message.senderId?styles.mine:""}`}>{message.body}{message.kind==="voice_note"&&message.url&&<audio controls src={message.url}/>}<span className={styles.time}>{new Date(message.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></article>)}</main>{conversationId&&<form className={styles.composer} onSubmit={send}><button className={styles.icon} type="button" onClick={()=>document.getElementById("chat-file")?.click()}>＋</button><input id="chat-file" type="file" hidden onChange={e=>setFile(e.target.files?.[0])}/><input value={text} onChange={e=>setText(e.target.value)} placeholder="Type a message"/><button className={styles.icon} type="button" onClick={toggleRecording}>🎙</button><button className={`${styles.icon} ${styles.send}`}>➤</button></form>}{callId&&<CallOverlay callSessionId={callId} onEnd={()=>{void communicationRepository.endCall(callId);setCallId(undefined);}}/>}</section>;
}
