"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { communicationRepository } from "@/lib/communication-repository";
import type { ChatMessage, Conversation } from "@/lib/types";
import { useMediaPermission } from "@/hooks/use-media-permission";
import { CallOverlay } from "./call-overlay";

export function ChatPanel() {
  const [conversations,setConversations]=useState<Conversation[]>([]); const [conversationId,setConversationId]=useState<string>(); const [messages,setMessages]=useState<ChatMessage[]>([]); const [text,setText]=useState(""); const [file,setFile]=useState<File>(); const [error,setError]=useState(""); const [callId,setCallId]=useState<string>(); const [recording,setRecording]=useState(false); const recorder=useRef<MediaRecorder | undefined>(undefined); const chunks=useRef<Blob[]>([]); const {request,stop,state}=useMediaPermission();
  const load=async()=>{try{const data=await communicationRepository.listConversations();setConversations(data);if(!conversationId&&data[0])setConversationId(data[0].id);}catch(e){setError(e instanceof Error?e.message:"Could not load messages.");}};
  useEffect(()=>{void load();},[]);
  useEffect(()=>{if(!conversationId)return;const refresh=async()=>{try{setMessages(await communicationRepository.messages(conversationId));await communicationRepository.read(conversationId);}catch(e){setError(e instanceof Error?e.message:"Could not load messages.");}};void refresh();const channel=communicationRepository.subscribe(conversationId,refresh);return()=>{void channel.unsubscribe();};},[conversationId]);
  const start=async()=>{try{const id=await communicationRepository.start();setConversationId(id);await load();}catch(e){setError(e instanceof Error?e.message:"Could not start support chat.");}};
  const send=async(e:FormEvent)=>{e.preventDefault();if(!conversationId||(!text&&!file))return;try{await communicationRepository.send(conversationId,text,file?.type.startsWith("image/")?"image":file?"file":"text",file);setText("");setFile(undefined);}catch(e){setError(e instanceof Error?e.message:"Could not send message.");}};
  const toggleRecording=async()=>{try{if(recording){recorder.current?.stop();return;}const stream=await request();chunks.current=[];const media=new MediaRecorder(stream);recorder.current=media;media.ondataavailable=e=>chunks.current.push(e.data);media.onstop=async()=>{setRecording(false);stop();const blob=new Blob(chunks.current,{type:media.mimeType||"audio/webm"});if(!conversationId)return;const voice=new File([blob],`voice-note-${Date.now()}.${media.mimeType.includes("mp4")?"m4a":"webm"}`,{type:blob.type});try{await communicationRepository.send(conversationId,"","voice_note",voice,Math.min(120000,Math.round((chunks.current.reduce((n,x)=>n+x.size,0)/16000)*1000)));}catch(e){setError(e instanceof Error?e.message:"Could not send voice note.");}};media.start();setRecording(true);}catch(e){setError(e instanceof Error?e.message:"Microphone access is required to record a voice note.");}};
  const call=async()=>{if(!conversationId)return;try{setCallId(await communicationRepository.requestCall(conversationId));}catch(e){setError(e instanceof Error?e.message:"Could not start call.");}};
  return <section className="team-panel"><p className="eyebrow">MESSAGES</p><h2>Support inbox</h2><p>Message the MarketApp support team securely.</p>{error&&<p className="note">{error}</p>}<button className="outline mini" onClick={start}>Start support chat</button><div className="team-table">{conversations.map(item=><button className="outline" key={item.id} onClick={()=>setConversationId(item.id)}>{item.title}</button>)}</div>{conversationId&&<><div className="attachments">{messages.map(message=><div key={message.id} className="note"><strong>{message.kind}:</strong> {message.body}{message.url&&message.kind!=="voice_note"&&<><br/><a href={message.url} target="_blank" rel="noreferrer">Open {message.fileName||"attachment"}</a></>}{message.kind==="voice_note"&&message.url&&<audio controls src={message.url}/>}</div>)}</div><form className="quote-form" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message"/><input type="file" onChange={e=>setFile(e.target.files?.[0])}/><div><button className="outline mini" type="button" onClick={toggleRecording}>{recording?"Stop recording":"Record voice note"}</button><button className="outline mini" type="button" onClick={call}>Start voice call</button><button className="primary mini">Send message</button></div>{state==="denied"&&<small>Allow microphone access in your browser settings to use voice features.</small>}</form></>}{callId&&<CallOverlay callSessionId={callId} onEnd={()=>{void communicationRepository.endCall(callId);setCallId(undefined);}}/>}</section>;
}
