"use client";
import { useEffect, useState } from "react";
import { ChatPanel } from "./chat-panel";
import styles from "./communication-dock.module.css";
import { communicationRepository } from "@/lib/communication-repository";
import { supabase } from "@/lib/supabase";
import { useBrowserNotifications } from "@/hooks/use-browser-notifications";
import { CallOverlay } from "./call-overlay";
export function CommunicationDock(){const [open,setOpen]=useState(false),[unread,setUnread]=useState(0),[availability,setAvailability]=useState<"available"|"busy">("busy"),[support,setSupport]=useState(false),[ringing,setRinging]=useState<string>();const {permission,enable,notify}=useBrowserNotifications();useEffect(()=>{let channel:any;void(async()=>{const user=(await supabase?.auth.getUser())?.data.user;if(!user)return;const profile=await supabase!.from("profiles").select("role").eq("id",user.id).single();const isSupport=profile.data?.role==="support_rep"||profile.data?.role==="super_admin";setSupport(isSupport);if(isSupport){setAvailability((await communicationRepository.availability()) as "available"|"busy");channel=communicationRepository.subscribeCalls(async()=>{const calls=await supabase!.from("call_sessions").select("id,status").eq("status","ringing");if(calls.data?.[0]&&availability==="available"){setRinging(calls.data[0].id);notify("MarketApp incoming call","A customer needs support");}});}setUnread(await communicationRepository.unreadCount());})();return()=>{void channel?.unsubscribe();};},[availability,notify]);const toggle=async()=>{if(!open&&permission==="default")await enable();setOpen(!open);};return <div className={styles.dock}>{ringing&&<div style={{position:"fixed",inset:0,zIndex:99,display:"grid",placeItems:"center",background:"#0f5132dd",color:"white"}}><div><h1>Incoming call</h1><button onClick={async()=>{await communicationRepository.acceptCall(ringing);setRinging(undefined);}}>Accept</button><button onClick={async()=>{await communicationRepository.rejectCall(ringing);setRinging(undefined);}}>Reject</button></div></div>}{open&&<div className={styles.panel}>{support&&<button className="outline mini" onClick={async()=>{const next=availability==="available"?"busy":"available";await communicationRepository.setAvailability(next);setAvailability(next);}}>{availability==="available"?"Available":"Busy"}</button>}<ChatPanel compact onMinimize={()=>setOpen(false)}/></div>}<button className={styles.launcher} onClick={toggle} aria-label={open?"Minimize messages":"Open messages"}>{unread>0&&<small>{unread}</small>}{open?"-":"M"}</button></div>}
