"use client";
import { useEffect, useMemo, useState } from "react";
import { orderRepository } from "@/lib/repositories";
import { statusLabel } from "@/lib/order-state";
import type { Order, OrderStatus, UserRole } from "@/lib/types";

const nav: Record<UserRole, string[]> = { admin: ["Overview", "Orders", "Vendors", "Riders", "Customers"], vendor: ["Requests", "My quotes", "Profile"], rider: ["My deliveries", "Completed", "Profile"], customer: ["Shop", "My orders", "Saved lists"] };
const titles: Record<UserRole, [string,string]> = { admin: ["Good morning, Zanni.", "Here’s the market pulse for today."], vendor: ["Your market is calling.", "Two fresh customer requests need a quote."], rider: ["Keep the city moving.", "You have two deliveries in motion today."], customer: ["What’s on your list?", "Your favourite market, without the market run."] };
const nextStatus: Partial<Record<OrderStatus, OrderStatus>> = { requested: "quoted", quoted: "confirmed", confirmed: "assigned", assigned: "picked_up", picked_up: "delivered" };

export function Dashboard({ role }: { role: UserRole }) {
  const [orders, setOrders] = useState<Order[]>([]); const [active, setActive] = useState("Overview"); const [message, setMessage] = useState("");
  const load = () => orderRepository.listOrders().then(setOrders); useEffect(() => { load(); }, []);
  const visibleOrders = useMemo(() => role === "vendor" ? orders.filter((o) => ["requested", "quoted"].includes(o.status)) : role === "rider" ? orders.filter((o) => o.rider === "Seyi A.") : role === "customer" ? orders.filter((o) => o.customerName === "Amara Okafor") : orders, [orders, role]);
  const advance = async (order: Order) => { const target = nextStatus[order.status]; if (!target) return; try { await orderRepository.updateStatus(order.id, target); setMessage(`${order.id} is now ${statusLabel(target).toLowerCase()}.`); load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not update order."); } };
  const assign = async (order: Order) => { try { await orderRepository.assignRider(order.id, "Seyi A."); setMessage(`${order.id} assigned to Seyi A.`); load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not assign rider."); } };
  return <main className="app-shell"><aside className="sidebar"><a className="brand" href={`/${role}`}><span>m</span> market<br />woman</a><p className="sidebar-label">WORKSPACE</p>{nav[role].map((item) => <button key={item} className={active === item ? "nav-link selected" : "nav-link"} onClick={() => setActive(item)}>{item}</button>)}<div className="profile"><span>{role[0].toUpperCase()}</span><div><strong>{role === "admin" ? "Zanni Zaddy" : role === "vendor" ? "Mama Chidinma" : role === "rider" ? "Seyi Ade" : "Amara Okafor"}</strong><small>{role}</small></div></div></aside>
  <section className="content"><header className="topbar"><div><p className="eyebrow">{role} WORKSPACE</p><h1>{titles[role][0]}</h1><p>{titles[role][1]}</p></div><button className="outline" onClick={() => { localStorage.removeItem("market-woman-role"); location.href = "/login"; }}>Switch role</button></header>
  {message && <div className="toast">{message}<button onClick={() => setMessage("")}>×</button></div>}
  {role === "admin" && <section className="stats"><Stat value={orders.length.toString()} label="Orders in motion" accent="coral"/><Stat value="₦73,800" label="Order value today" accent="gold"/><Stat value="18 min" label="Average response" accent="green"/></section>}
  {role === "customer" && <section className="order-callout"><div><p className="eyebrow">NEW ORDER</p><h2>Send your shopping list</h2><p>Type it out, attach a photo, and a market woman will take it from there.</p></div><button className="primary" onClick={() => setMessage("Shopping-list form is the next customer-facing build card.")}>Start a list →</button></section>}
  <section className="orders-section"><div className="section-heading"><div><p className="eyebrow">{active.toUpperCase()}</p><h2>{role === "admin" ? "Orders that need attention" : role === "vendor" ? "Fresh market requests" : role === "rider" ? "Your active deliveries" : "Your latest order"}</h2></div><span className="count">{visibleOrders.length} items</span></div><div className="order-grid">{visibleOrders.map((order) => <article className="order-card" key={order.id}><div className="card-top"><span className={`status ${order.status}`}>{statusLabel(order.status)}</span><small>{order.id}</small></div><h3>{order.customerName}</h3><p className="area">⌖ {order.area} · {order.createdAt}</p><ul>{order.items.slice(0, 2).map((item) => <li key={item}>{item}</li>)}{order.items.length > 2 && <li>+ {order.items.length - 2} more item</li>}</ul>{order.total && <strong className="total">₦{order.total.toLocaleString()}</strong>}<div className="card-actions">{role === "admin" && order.status === "confirmed" && <button className="primary" onClick={() => assign(order)}>Assign rider</button>}{role !== "customer" && nextStatus[order.status] && <button className="outline" onClick={() => advance(order)}>{order.status === "requested" ? "Review quote" : `Mark ${statusLabel(nextStatus[order.status]!).toLowerCase()}`}</button>}{role === "customer" && <button className="outline" onClick={() => setMessage(`Order ${order.id} is currently ${statusLabel(order.status).toLowerCase()}.`)}>Track order</button>}</div></article>)}</div>{!visibleOrders.length && <div className="empty">No orders match this workspace yet.</div>}</section></section></main>;
}
function Stat({ value, label, accent }: { value: string; label: string; accent: string }) { return <article className={`stat ${accent}`}><strong>{value}</strong><span>{label}</span></article>; }
