import { supabase } from "./supabase";
import type { CallSession, ChatMessage, Conversation, MessageKind } from "./types";
const client = () => { if (!supabase) throw new Error("Supabase is not configured."); return supabase; };
export const communicationRepository = {
  async listConversations(): Promise<Conversation[]> { const { data, error } = await client().from("conversations").select("id,kind,last_message_at").order("last_message_at", { ascending:false }); if(error) throw error; return (data??[]).map((x:any)=>({id:x.id,kind:x.kind,title:x.kind.replaceAll("_"," "),lastMessageAt:x.last_message_at,unreadCount:0})); },
  async start(): Promise<string> { const {data:{user}}=await client().auth.getUser(); if(!user) throw new Error("Sign in is required."); const {data,error}=await client().rpc("start_support_conversation",{target_id:user.id}); if(error) throw error; return data; },
  async messages(conversationId:string): Promise<ChatMessage[]> { const {data,error}=await client().from("conversation_messages").select("id,conversation_id,sender_id,kind,body,storage_path,file_name,mime_type,duration_ms,created_at").eq("conversation_id",conversationId).order("created_at"); if(error) throw error; return Promise.all((data??[]).map(async(x:any)=>{let url:string|undefined; if(x.storage_path){const signed=await client().storage.from("chat-media").createSignedUrl(x.storage_path,900);url=signed.data?.signedUrl;} return {id:x.id,conversationId:x.conversation_id,senderId:x.sender_id,kind:x.kind,body:x.body??undefined,fileName:x.file_name??undefined,mimeType:x.mime_type??undefined,durationMs:x.duration_ms??undefined,url,createdAt:x.created_at};})); },
  async send(conversationId:string, body:string, kind:MessageKind="text", file?:File, durationMs?:number) { let path:string|undefined; if(file){path=`${conversationId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`; const {error}=await client().storage.from("chat-media").upload(path,file,{contentType:file.type});if(error)throw error;} const {error}=await client().rpc("send_conversation_message",{conversation:conversationId,message_kind:kind,message_body:body||null,media_path:path||null,media_name:file?.name||null,media_type:file?.type||null,note_duration:durationMs||null});if(error)throw error; },
  async read(conversationId:string){const {error}=await client().rpc("mark_conversation_read",{conversation:conversationId});if(error)throw error;},
  async requestCall(conversationId:string):Promise<string>{const {data,error}=await client().rpc("request_call",{conversation:conversationId});if(error)throw error;return data;},
  subscribe(conversationId:string,onChange:()=>void){return client().channel(`conversation:${conversationId}`).on("postgres_changes",{event:"*",schema:"public",table:"conversation_messages",filter:`conversation_id=eq.${conversationId}`},onChange).subscribe();}
};
